# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('IOT_id', models.CharField(default='-1', max_length=20)),
                ('gps_lat', models.CharField(max_length=20)),
                ('gps_long', models.CharField(max_length=20)),
                ('gps_elev', models.CharField(max_length=20)),
                ('heading_point', models.CharField(max_length=20)),
            ],
        ),
    ]
